In [32]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import time

In [33]:
from Fed_up import test

# Auto-Analysis

In [34]:
vectorizors = ['count', 'tfidf']
redutors = ['svd', 'nmf']

In [44]:
outputs = pd.DataFrame(columns=['vectorizor', 'redutor', 'ngram', 'min_df', 'max_df', 
                                'rating_mae', 'rating_le', 'like_accuracy', 'like_precision', 
                                'like_recall', 'like_f1', 'size', 'time'])

In [45]:
# Baseline

start = time.time()
data, metrics = test.run_test(predict = False, sample = 200, local=True)
end = time.time()
duration = end - start

new_row = {'vectorizor': '-', 'redutor': '-', 'ngram': '-', 'min_df': '-', 'max_df': '-', 
           'rating_mae': metrics['rating_mae'], 'rating_le': metrics['rating_le'], 
           'like_accuracy': metrics['like_accuracy'], 'like_precision': metrics['like_precision'], 
           'like_recall': metrics['like_recall'], 'like_f1': metrics['like_f1'], 
           'size': len(data), 'time': duration}

outputs = outputs.append(new_row, ignore_index=True)

Fetching the test inputs...
Calculating predictions...
Preparing results dataframe...
Cleaning up failed scores...
Iterating and filling results dataframe...
Saving results dataframe...
Calculating metrics for tests...

In [46]:
outputs

,vectorizor,redutor,ngram,min_df,max_df,rating_mae,rating_le,like_accuracy,like_precision,like_recall,like_f1,size,time
0,-,-,-,-,-,0.53,0.05,0.88,0.936,0.936,0.936,200,0.234074

In [47]:
import time

for v in vectorizors:
    for r in redutors:
            
        start = time.time()
        data, metrics = test.run_test(sample = 50, vectorizer = v, dimred = r)
        end = time.time()
        duration = end - start

        new_row = {'vectorizor': v, 'redutor': r, 'ngram': (1,1), 'min_df': 1, 'max_df': 1.0, 
                   'rating_mae': metrics['rating_mae'], 'rating_le': metrics['rating_le'], 
                   'like_accuracy': metrics['like_accuracy'], 'like_precision': metrics['like_precision'], 
                   'like_recall': metrics['like_recall'], 'like_f1': metrics['like_f1'], 
                   'size': len(data), 'time': duration}

        outputs = outputs.append(new_row, ignore_index=True)
        print("")
        display(outputs)
        print("")

Fetching the test inputs...
Calculating predictions...
> (12471) Prediction for user 375894 done: 0.749!
> (19992) Prediction for user 831612 done: 0.576!
> (25450) Prediction for user 1608793 done: 0.165!
> (6494) Prediction for user 183942 done: 0.407!
> (3265) Prediction for user 92295 done: 0.737!
> (19949) Prediction for user 828089 done: 0.21!
> (7085) Prediction for user 200171 done: 0.232!
> (10341) Prediction for user 304561 done: 0.306!
> (26205) Prediction for user 1813203 done: 0.385!
> (11462) Prediction for user 343641 not found!
> (24413) Prediction for user 1393592 done: 0.534!
> (25873) Prediction for user 1698075 done: 0.384!
> (3122) Prediction for user 88028 done: 0.364!
> (16444) Prediction for user 578971 done: 0.521!
> (27757) Prediction for user 1800310325 done: 0.427!
> (7497) Prediction for user 212478 done: 0.456!
> (17092) Prediction for user 616120 done: 0.185!
> (12947) Prediction for user 400411 done: 0.271!
> (8908) Prediction for user 251719 not found!
> (23163) Prediction for user 1206943 done: 0.131!
> (7117) Prediction for user 200957 done: 0.302!
> (12930) Prediction for user 399552 done: 0.365!
> (20663) Prediction for user 892333 done: 0.489!
> (11702) Prediction for user 350629 done: 0.4!
> (19809) Prediction for user 814605 done: 0.61!
> (9534) Prediction for user 275742 done: 0.426!
> (15127) Prediction for user 506345 done: 0.791!
> (4375) Prediction for user 124449 not found!
> (2797) Prediction for user 78128 done: 0.73!
> (23603) Prediction for user 1267223 done: 0.369!
> (27072) Prediction for user 2389596 done: 0.199!
> (12549) Prediction for user 379050 done: 0.525!
> (16765) Prediction for user 596266 done: 0.542!
> (27574) Prediction for user 2920261 done: 0.074!
> (11436) Prediction for user 342580 done: 0.594!
> (18594) Prediction for user 722385 done: 0.411!
> (16845) Prediction for user 600932 done: 0.608!
> (12052) Prediction for user 360471 done: 0.814!
> (6531) Prediction for user 184819 done: 0.583!
> (1246) Prediction for user 41560 done: 0.424!
> (26606) Prediction for user 2016747 done: 0.513!
> (18131) Prediction for user 687302 done: 0.633!
> (26888) Prediction for user 2226346 done: 0.294!
> (18948) Prediction for user 745004 done: 0.135!
> (96) Prediction for user 8619 done: 0.382!
> (12140) Prediction for user 363497 done: 0.255!
> (24747) Prediction for user 1458120 done: 0.498!
> (11935) Prediction for user 357014 done: 0.255!
> (20717) Prediction for user 898160 done: 0.34!
> (18696) Prediction for user 729188 done: 0.322!
Preparing results dataframe...
Cleaning up failed scores...
Iterating and filling results dataframe...
Saving results dataframe...
Uploaded test_outputs_20201122_1608.csv to GCP!
Calculating metrics for tests...

,vectorizor,redutor,ngram,min_df,max_df,rating_mae,rating_le,like_accuracy,like_precision,like_recall,like_f1,size,time
0,-,-,-,-,-,0.53,0.05,0.88,0.936,0.936,0.936,200,0.234074
1,count,svd,"(1, 1)",1,1,0.34,0.00,1.00,1.000,1.000,1.000,47,2267.181228

Fetching the test inputs...
Calculating predictions...
> (12471) Prediction for user 375894 done: 0.753!
> (19992) Prediction for user 831612 done: 0.576!
> (25450) Prediction for user 1608793 done: 0.164!
> (6494) Prediction for user 183942 done: 0.402!
> (3265) Prediction for user 92295 done: 0.738!
> (19949) Prediction for user 828089 done: 0.189!
> (7085) Prediction for user 200171 done: 0.228!
> (10341) Prediction for user 304561 done: 0.305!
> (26205) Prediction for user 1813203 done: 0.449!
> (11462) Prediction for user 343641 not found!
> (24413) Prediction for user 1393592 done: 0.54!
> (25873) Prediction for user 1698075 done: 0.38!
> (3122) Prediction for user 88028 done: 0.367!
> (16444) Prediction for user 578971 done: 0.521!
> (27757) Prediction for user 1800310325 done: 0.427!
> (7497) Prediction for user 212478 done: 0.464!
> (17092) Prediction for user 616120 done: 0.18!
> (12947) Prediction for user 400411 done: 0.284!
> (8908) Prediction for user 251719 not found!
> (23163) Prediction for user 1206943 done: 0.126!
> (7117) Prediction for user 200957 done: 0.324!
> (12930) Prediction for user 399552 done: 0.371!
> (20663) Prediction for user 892333 done: 0.537!
> (11702) Prediction for user 350629 done: 0.387!
> (19809) Prediction for user 814605 done: 0.612!
> (9534) Prediction for user 275742 done: 0.465!
> (15127) Prediction for user 506345 done: 0.791!
> (4375) Prediction for user 124449 not found!
> (2797) Prediction for user 78128 done: 0.733!
> (23603) Prediction for user 1267223 done: 0.432!
> (27072) Prediction for user 2389596 done: 0.21!
> (12549) Prediction for user 379050 done: 0.527!
> (16765) Prediction for user 596266 done: 0.538!
> (27574) Prediction for user 2920261 done: 0.07!
> (11436) Prediction for user 342580 done: 0.602!
> (18594) Prediction for user 722385 done: 0.415!
> (16845) Prediction for user 600932 done: 0.608!
> (12052) Prediction for user 360471 done: 0.814!
> (6531) Prediction for user 184819 done: 0.562!
> (1246) Prediction for user 41560 done: 0.394!
> (26606) Prediction for user 2016747 done: 0.485!
> (18131) Prediction for user 687302 done: 0.665!
> (26888) Prediction for user 2226346 done: 0.306!
> (18948) Prediction for user 745004 done: 0.135!
> (96) Prediction for user 8619 done: 0.378!
> (12140) Prediction for user 363497 done: 0.249!
> (24747) Prediction for user 1458120 done: 0.504!
> (11935) Prediction for user 357014 done: 0.259!
> (20717) Prediction for user 898160 done: 0.305!
> (18696) Prediction for user 729188 done: 0.32!
Preparing results dataframe...
Cleaning up failed scores...
Iterating and filling results dataframe...
Saving results dataframe...
Uploaded test_outputs_20201122_1644.csv to GCP!
Calculating metrics for tests...

,vectorizor,redutor,ngram,min_df,max_df,rating_mae,rating_le,like_accuracy,like_precision,like_recall,like_f1,size,time
0,-,-,-,-,-,0.53,0.05,0.88,0.936,0.936,0.936,200,0.234074
1,count,svd,"(1, 1)",1,1,0.34,0.00,1.00,1.000,1.000,1.000,47,2267.181228
2,count,nmf,"(1, 1)",1,1,0.34,0.00,1.00,1.000,1.000,1.000,47,2140.428584

Fetching the test inputs...
Calculating predictions...
> (12471) Prediction for user 375894 done: 0.748!
> (19992) Prediction for user 831612 done: 0.576!
> (25450) Prediction for user 1608793 done: 0.171!
> (6494) Prediction for user 183942 done: 0.41!
> (3265) Prediction for user 92295 done: 0.741!
> (19949) Prediction for user 828089 done: 0.213!
> (7085) Prediction for user 200171 done: 0.227!
> (10341) Prediction for user 304561 done: 0.304!
> (26205) Prediction for user 1813203 done: 0.489!
> (11462) Prediction for user 343641 not found!
> (24413) Prediction for user 1393592 done: 0.529!
> (25873) Prediction for user 1698075 done: 0.382!
> (3122) Prediction for user 88028 done: 0.369!
> (16444) Prediction for user 578971 done: 0.518!
> (27757) Prediction for user 1800310325 done: 0.417!
> (7497) Prediction for user 212478 done: 0.434!
> (17092) Prediction for user 616120 done: 0.181!
> (12947) Prediction for user 400411 done: 0.276!
> (8908) Prediction for user 251719 not found!
> (23163) Prediction for user 1206943 done: 0.127!
> (7117) Prediction for user 200957 done: 0.302!
> (12930) Prediction for user 399552 done: 0.378!
> (20663) Prediction for user 892333 done: 0.589!
> (11702) Prediction for user 350629 done: 0.388!
> (19809) Prediction for user 814605 done: 0.619!
> (9534) Prediction for user 275742 done: 0.461!
> (15127) Prediction for user 506345 done: 0.767!
> (4375) Prediction for user 124449 not found!
> (2797) Prediction for user 78128 done: 0.729!
> (23603) Prediction for user 1267223 done: 0.425!
> (27072) Prediction for user 2389596 done: 0.204!
> (12549) Prediction for user 379050 done: 0.518!
> (16765) Prediction for user 596266 done: 0.537!
> (27574) Prediction for user 2920261 done: 0.0!
> (11436) Prediction for user 342580 done: 0.606!
> (18594) Prediction for user 722385 done: 0.413!
> (16845) Prediction for user 600932 done: 0.608!
> (12052) Prediction for user 360471 done: 0.82!
> (6531) Prediction for user 184819 done: 0.605!
> (1246) Prediction for user 41560 done: 0.401!
> (26606) Prediction for user 2016747 done: 0.51!
> (18131) Prediction for user 687302 done: 0.659!
> (26888) Prediction for user 2226346 done: 0.303!
> (18948) Prediction for user 745004 done: 0.134!
> (96) Prediction for user 8619 done: 0.374!
> (12140) Prediction for user 363497 done: 0.26!
> (24747) Prediction for user 1458120 done: 0.499!
> (11935) Prediction for user 357014 done: 0.244!
> (20717) Prediction for user 898160 done: 0.309!
> (18696) Prediction for user 729188 done: 0.325!
Preparing results dataframe...
Cleaning up failed scores...
Iterating and filling results dataframe...
Saving results dataframe...
Uploaded test_outputs_20201122_1717.csv to GCP!
Calculating metrics for tests...

,vectorizor,redutor,ngram,min_df,max_df,rating_mae,rating_le,like_accuracy,like_precision,like_recall,like_f1,size,time
0,-,-,-,-,-,0.53,0.05,0.88,0.936,0.936,0.936,200,0.234074
1,count,svd,"(1, 1)",1,1,0.34,0.00,1.00,1.000,1.000,1.000,47,2267.181228
2,count,nmf,"(1, 1)",1,1,0.34,0.00,1.00,1.000,1.000,1.000,47,2140.428584
3,tfidf,svd,"(1, 1)",1,1,0.34,0.00,1.00,1.000,1.000,1.000,47,1975.318266

Fetching the test inputs...
Calculating predictions...
> (12471) Prediction for user 375894 done: 0.746!
> (19992) Prediction for user 831612 done: 0.574!
> (25450) Prediction for user 1608793 done: 0.165!
> (6494) Prediction for user 183942 done: 0.458!
> (3265) Prediction for user 92295 done: 0.743!
> (19949) Prediction for user 828089 done: 0.196!
> (7085) Prediction for user 200171 done: 0.238!
> (10341) Prediction for user 304561 done: 0.304!
> (26205) Prediction for user 1813203 done: 0.339!
> (11462) Prediction for user 343641 not found!
> (24413) Prediction for user 1393592 done: 0.539!
> (25873) Prediction for user 1698075 done: 0.378!
> (3122) Prediction for user 88028 done: 0.388!
> (16444) Prediction for user 578971 done: 0.521!
> (27757) Prediction for user 1800310325 done: 0.415!
> (7497) Prediction for user 212478 done: 0.426!
> (17092) Prediction for user 616120 done: 0.18!
> (12947) Prediction for user 400411 done: 0.267!
> (8908) Prediction for user 251719 not found!
> (23163) Prediction for user 1206943 done: 0.127!
> (7117) Prediction for user 200957 done: 0.375!
> (12930) Prediction for user 399552 done: 0.342!
> (20663) Prediction for user 892333 done: 0.58!
> (11702) Prediction for user 350629 done: 0.397!
> (19809) Prediction for user 814605 done: 0.617!
> (9534) Prediction for user 275742 done: 0.434!
> (15127) Prediction for user 506345 done: 0.706!
> (4375) Prediction for user 124449 not found!
> (2797) Prediction for user 78128 done: 0.737!
> (23603) Prediction for user 1267223 done: 0.391!
> (27072) Prediction for user 2389596 done: 0.205!
> (12549) Prediction for user 379050 done: 0.519!
> (16765) Prediction for user 596266 done: 0.539!
> (27574) Prediction for user 2920261 done: 0.076!
> (11436) Prediction for user 342580 done: 0.598!
> (18594) Prediction for user 722385 done: 0.408!
> (16845) Prediction for user 600932 done: 0.615!
> (12052) Prediction for user 360471 done: 0.809!
> (6531) Prediction for user 184819 done: 0.582!
> (1246) Prediction for user 41560 done: 0.395!
> (26606) Prediction for user 2016747 done: 0.547!
> (18131) Prediction for user 687302 done: 0.69!
> (26888) Prediction for user 2226346 done: 0.305!
> (18948) Prediction for user 745004 done: 0.131!
> (96) Prediction for user 8619 done: 0.385!
> (12140) Prediction for user 363497 done: 0.27!
> (24747) Prediction for user 1458120 done: 0.507!
> (11935) Prediction for user 357014 done: 0.26!
> (20717) Prediction for user 898160 done: 0.308!
> (18696) Prediction for user 729188 done: 0.326!
Preparing results dataframe...
Cleaning up failed scores...
Iterating and filling results dataframe...
Saving results dataframe...
Uploaded test_outputs_20201122_1751.csv to GCP!
Calculating metrics for tests...

,vectorizor,redutor,ngram,min_df,max_df,rating_mae,rating_le,like_accuracy,like_precision,like_recall,like_f1,size,time
0,-,-,-,-,-,0.53,0.05,0.88,0.936,0.936,0.936,200,0.234074
1,count,svd,"(1, 1)",1,1,0.34,0.00,1.00,1.000,1.000,1.000,47,2267.181228
2,count,nmf,"(1, 1)",1,1,0.34,0.00,1.00,1.000,1.000,1.000,47,2140.428584
3,tfidf,svd,"(1, 1)",1,1,0.34,0.00,1.00,1.000,1.000,1.000,47,1975.318266
4,tfidf,nmf,"(1, 1)",1,1,0.34,0.00,1.00,1.000,1.000,1.000,47,2042.936509

# Vectorizer vs. Dimred

In [10]:
start = time.time()
input_df, output_df = test.run_recommendations(user_id=235291, collaborative=0.5, clear_neg=False,
                    vectorizer = 'count', dimred = 'svd', ngram = (1,1), min_df = 1, max_df = 1.0, local = True)
end = time.time()
duration = end - start
print(duration)

  recipe_id                               name liked
0     16741             aunt bee s lentil soup     1
1     10744          delicious chicken pot pie     1
2     16575  just the best barbecue sauce ever     0
3     22782   jo mama s world famous spaghetti     1
4    107997       4 minute spicy garlic shrimp     1
5    212500               mushroom noodle soup     1
6    208930             mary s chiles rellenos     1

,recipe_id,name,content,collaborative,hybrid,rec_score
0,383814,baked cod casserole,1.814424,1.444563,1.629494,1.000
1,255836,chicken parmigina,2.065884,1.014228,1.540056,0.943
2,411372,caesar salad dressing no egg,1.399572,1.510044,1.454808,0.889
3,281914,root vegetables casserole for winter,1.983682,0.794778,1.389230,0.847
4,76593,weymo s accelerated version of grannie s turke...,1.727159,1.042752,1.384956,0.845
5,51887,feta stuffed chicken with green olives,1.646257,1.010838,1.328547,0.809
6,238415,chicken and rosemary cream rigatoni,1.624943,1.014411,1.319677,0.803
7,197905,angel hair pasta with pesto and tomatoes,1.624163,1.010689,1.317426,0.802
8,429766,celery bisque with stilton toasts,1.546723,1.074735,1.310729,0.797
9,367934,chris grilled jalapeno wraps,1.395702,1.203057,1.299380,0.790

45.56931686401367

In [11]:
start = time.time()
input_df_2, output_df_2 = test.run_recommendations(user_id=235291, collaborative=0.5, clear_neg=False,
                    vectorizer = 'tfidf', dimred = 'svd', ngram = (1,1), min_df = 1, max_df = 1.0, local = True)
end = time.time()
duration = end - start
print(duration)

  recipe_id                               name liked
0     16741             aunt bee s lentil soup     1
1     10744          delicious chicken pot pie     1
2     16575  just the best barbecue sauce ever     0
3     22782   jo mama s world famous spaghetti     1
4    107997       4 minute spicy garlic shrimp     1
5    212500               mushroom noodle soup     1
6    208930             mary s chiles rellenos     1

,recipe_id,name,content,collaborative,hybrid,rec_score
0,383814,baked cod casserole,1.812720,1.351820,1.582270,1.000
1,255836,chicken parmigina,2.069633,1.023574,1.546603,0.977
2,411372,caesar salad dressing no egg,1.411734,1.511110,1.461422,0.922
3,76593,weymo s accelerated version of grannie s turke...,1.717885,1.031934,1.374910,0.865
4,281914,root vegetables casserole for winter,1.982042,0.727580,1.354811,0.852
5,197905,angel hair pasta with pesto and tomatoes,1.637881,1.022045,1.329963,0.836
6,238415,chicken and rosemary cream rigatoni,1.634156,1.023646,1.328901,0.836
7,51887,feta stuffed chicken with green olives,1.634542,1.021535,1.328039,0.835
8,429766,celery bisque with stilton toasts,1.552704,1.068719,1.310711,0.824
9,36758,chinese chicken chow bake,1.590213,1.023203,1.306708,0.821

40.94865798950195

In [12]:
start = time.time()
input_df_3, output_df_3 = test.run_recommendations(user_id=235291, collaborative=0.5, clear_neg=False,
                    vectorizer = 'count', dimred = 'nmf', ngram = (1,1), min_df = 1, max_df = 1.0, local = True)
end = time.time()
duration = end - start
print(duration)

  recipe_id                               name liked
0     16741             aunt bee s lentil soup     1
1     10744          delicious chicken pot pie     1
2     16575  just the best barbecue sauce ever     0
3     22782   jo mama s world famous spaghetti     1
4    107997       4 minute spicy garlic shrimp     1
5    212500               mushroom noodle soup     1
6    208930             mary s chiles rellenos     1

,recipe_id,name,content,collaborative,hybrid,rec_score
0,383814,baked cod casserole,1.804481,1.399247,1.601864,1.000
1,255836,chicken parmigina,2.068661,1.008558,1.538610,0.960
2,411372,caesar salad dressing no egg,1.419645,1.503009,1.461327,0.910
3,281914,root vegetables casserole for winter,1.983159,0.792841,1.388000,0.864
4,76593,weymo s accelerated version of grannie s turke...,1.724714,1.034124,1.379419,0.858
5,51887,feta stuffed chicken with green olives,1.634836,1.004489,1.319663,0.820
6,197905,angel hair pasta with pesto and tomatoes,1.631047,1.003464,1.317255,0.819
7,238415,chicken and rosemary cream rigatoni,1.624935,1.008617,1.316776,0.818
8,36758,chinese chicken chow bake,1.602993,1.009668,1.306330,0.812
9,367934,chris grilled jalapeno wraps,1.402567,1.206784,1.304676,0.811

48.28834581375122

In [13]:
start = time.time()
input_df_4, output_df_4 = test.run_recommendations(user_id=235291, collaborative=0.5, clear_neg=False,
                    vectorizer = 'tfidf', dimred = 'nmf', ngram = (1,1), min_df = 1, max_df = 1.0, local = True)
end = time.time()
duration = end - start
print(duration)

  recipe_id                               name liked
0     16741             aunt bee s lentil soup     1
1     10744          delicious chicken pot pie     1
2     16575  just the best barbecue sauce ever     0
3     22782   jo mama s world famous spaghetti     1
4    107997       4 minute spicy garlic shrimp     1
5    212500               mushroom noodle soup     1
6    208930             mary s chiles rellenos     1

,recipe_id,name,content,collaborative,hybrid,rec_score
0,383814,baked cod casserole,1.803370,1.442086,1.622728,1.000
1,255836,chicken parmigina,2.077483,1.013367,1.545425,0.953
2,411372,caesar salad dressing no egg,1.410990,1.508164,1.459577,0.901
3,281914,root vegetables casserole for winter,1.970942,0.806263,1.388603,0.858
4,76593,weymo s accelerated version of grannie s turke...,1.712338,1.038987,1.375663,0.850
5,238415,chicken and rosemary cream rigatoni,1.631536,1.013356,1.322446,0.818
6,51887,feta stuffed chicken with green olives,1.628495,1.010034,1.319265,0.816
7,36758,chinese chicken chow bake,1.590303,1.042748,1.316525,0.814
8,197905,angel hair pasta with pesto and tomatoes,1.620729,1.010514,1.315622,0.814
9,429766,celery bisque with stilton toasts,1.548950,1.073341,1.311146,0.811

52.86625409126282

# Optimizing

In [14]:
start = time.time()
input_df_2, output_df_2 = test.run_recommendations(user_id=235291, collaborative=0.5, clear_neg=False,
                    vectorizer = 'tfidf', dimred = 'svd', ngram = (1,1), min_df = 1, max_df = 1.0, local = True)
end = time.time()
duration = end - start
print(duration)

  recipe_id                               name liked
0     16741             aunt bee s lentil soup     1
1     10744          delicious chicken pot pie     1
2     16575  just the best barbecue sauce ever     0
3     22782   jo mama s world famous spaghetti     1
4    107997       4 minute spicy garlic shrimp     1
5    212500               mushroom noodle soup     1
6    208930             mary s chiles rellenos     1

,recipe_id,name,content,collaborative,hybrid,rec_score
0,383814,baked cod casserole,1.799415,1.292741,1.546078,1.000
1,255836,chicken parmigina,2.068178,1.015630,1.541904,0.997
2,411372,caesar salad dressing no egg,1.405879,1.488028,1.446954,0.933
3,76593,weymo s accelerated version of grannie s turke...,1.724876,1.034041,1.379458,0.888
4,281914,root vegetables casserole for winter,1.996500,0.747760,1.372130,0.883
5,51887,feta stuffed chicken with green olives,1.639412,1.012712,1.326062,0.851
6,238415,chicken and rosemary cream rigatoni,1.629697,1.015504,1.322600,0.849
7,197905,angel hair pasta with pesto and tomatoes,1.631699,1.011642,1.321670,0.849
8,429766,celery bisque with stilton toasts,1.551364,1.047182,1.299273,0.833
9,367934,chris grilled jalapeno wraps,1.396621,1.184699,1.290660,0.828

43.17187714576721

## Ngrams

In [15]:
start = time.time()
input_df_2_1, output_df_2_1 = test.run_recommendations(user_id=235291, collaborative=0.5, clear_neg=False,
                    vectorizer = 'tfidf', dimred = 'svd', ngram = (1,2), min_df = 1, max_df = 1.0, local = True)
end = time.time()
duration = end - start
print(duration)

  recipe_id                               name liked
0     16741             aunt bee s lentil soup     1
1     10744          delicious chicken pot pie     1
2     16575  just the best barbecue sauce ever     0
3     22782   jo mama s world famous spaghetti     1
4    107997       4 minute spicy garlic shrimp     1
5    212500               mushroom noodle soup     1
6    208930             mary s chiles rellenos     1

,recipe_id,name,content,collaborative,hybrid,rec_score
0,383814,baked cod casserole,1.815435,1.462691,1.639063,1.000
1,255836,chicken parmigina,2.072711,1.047541,1.560126,0.949
2,411372,caesar salad dressing no egg,1.405543,1.517332,1.461437,0.885
3,281914,root vegetables casserole for winter,1.993451,0.801946,1.397699,0.843
4,76593,weymo s accelerated version of grannie s turke...,1.720469,1.041556,1.381012,0.832
5,51887,feta stuffed chicken with green olives,1.637296,1.046714,1.342005,0.807
6,238415,chicken and rosemary cream rigatoni,1.634061,1.047415,1.340738,0.806
7,197905,angel hair pasta with pesto and tomatoes,1.628685,1.045908,1.337296,0.804
8,367934,chris grilled jalapeno wraps,1.406448,1.200186,1.303317,0.782
9,429766,celery bisque with stilton toasts,1.543039,1.057967,1.300503,0.780

43.75019192695618

In [16]:
start = time.time()
input_df_2_2, output_df_2_2 = test.run_recommendations(user_id=235291, collaborative=0.5, clear_neg=False,
                    vectorizer = 'tfidf', dimred = 'svd', ngram = (2,2), min_df = 1, max_df = 1.0, local = True)
end = time.time()
duration = end - start
print(duration)

  recipe_id                               name liked
0     16741             aunt bee s lentil soup     1
1     10744          delicious chicken pot pie     1
2     16575  just the best barbecue sauce ever     0
3     22782   jo mama s world famous spaghetti     1
4    107997       4 minute spicy garlic shrimp     1
5    212500               mushroom noodle soup     1
6    208930             mary s chiles rellenos     1

,recipe_id,name,content,collaborative,hybrid,rec_score
0,383814,baked cod casserole,1.799730,1.389182,1.594456,1.000
1,255836,chicken parmigina,2.070185,1.010744,1.540464,0.966
2,411372,caesar salad dressing no egg,1.411464,1.493280,1.452372,0.910
3,76593,weymo s accelerated version of grannie s turke...,1.724430,1.036343,1.380387,0.864
4,281914,root vegetables casserole for winter,1.985222,0.764583,1.374902,0.861
5,51887,feta stuffed chicken with green olives,1.634072,1.006198,1.320135,0.826
6,238415,chicken and rosemary cream rigatoni,1.629041,1.010561,1.319801,0.826
7,197905,angel hair pasta with pesto and tomatoes,1.615642,1.006961,1.311301,0.820
8,429766,celery bisque with stilton toasts,1.541539,1.057213,1.299376,0.813
9,367934,chris grilled jalapeno wraps,1.403121,1.183969,1.293545,0.809

47.68640208244324

In [17]:
start = time.time()
input_df_2_3, output_df_2_3 = test.run_recommendations(user_id=235291, collaborative=0.5, clear_neg=False,
                    vectorizer = 'tfidf', dimred = 'svd', ngram = (1,1), min_df = 0.10, max_df = 1.0, local = True)
end = time.time()
duration = end - start
print(duration)

  recipe_id                               name liked
0     16741             aunt bee s lentil soup     1
1     10744          delicious chicken pot pie     1
2     16575  just the best barbecue sauce ever     0
3     22782   jo mama s world famous spaghetti     1
4    107997       4 minute spicy garlic shrimp     1
5    212500               mushroom noodle soup     1
6    208930             mary s chiles rellenos     1

,recipe_id,name,content,collaborative,hybrid,rec_score
0,383814,baked cod casserole,1.803077,1.432329,1.617703,1.000
1,255836,chicken parmigina,2.082194,1.023432,1.552813,0.959
2,411372,caesar salad dressing no egg,1.410214,1.522333,1.466274,0.905
3,281914,root vegetables casserole for winter,1.982024,0.782741,1.382382,0.852
4,76593,weymo s accelerated version of grannie s turke...,1.722312,1.039813,1.381062,0.851
5,238415,chicken and rosemary cream rigatoni,1.634607,1.023336,1.328972,0.818
6,197905,angel hair pasta with pesto and tomatoes,1.624055,1.020415,1.322235,0.814
7,51887,feta stuffed chicken with green olives,1.620739,1.020235,1.320487,0.813
8,429766,celery bisque with stilton toasts,1.543453,1.085299,1.314376,0.809
9,36758,chinese chicken chow bake,1.579060,1.032457,1.305758,0.804

41.582533836364746

In [18]:
start = time.time()
input_df_2_3, output_df_2_3 = test.run_recommendations(user_id=235291, collaborative=0.5, clear_neg=False,
                    vectorizer = 'tfidf', dimred = 'svd', ngram = (1,1), min_df = 0.20, max_df = 1.0, local = True)
end = time.time()
duration = end - start
print(duration)

  recipe_id                               name liked
0     16741             aunt bee s lentil soup     1
1     10744          delicious chicken pot pie     1
2     16575  just the best barbecue sauce ever     0
3     22782   jo mama s world famous spaghetti     1
4    107997       4 minute spicy garlic shrimp     1
5    212500               mushroom noodle soup     1
6    208930             mary s chiles rellenos     1

,recipe_id,name,content,collaborative,hybrid,rec_score
0,383814,baked cod casserole,1.799785,1.337662,1.568723,1.000
1,255836,chicken parmigina,2.083157,1.002191,1.542674,0.983
2,411372,caesar salad dressing no egg,1.407436,1.512028,1.459732,0.929
3,76593,weymo s accelerated version of grannie s turke...,1.720726,1.031850,1.376288,0.875
4,281914,root vegetables casserole for winter,1.988745,0.752887,1.370816,0.872
5,238415,chicken and rosemary cream rigatoni,1.633033,1.002391,1.317712,0.837
6,51887,feta stuffed chicken with green olives,1.627745,0.996857,1.312301,0.834
7,429766,celery bisque with stilton toasts,1.530603,1.087191,1.308897,0.831
8,197905,angel hair pasta with pesto and tomatoes,1.615195,0.997793,1.306494,0.830
9,367934,chris grilled jalapeno wraps,1.412246,1.192171,1.302209,0.827

55.923585653305054

In [19]:
start = time.time()
input_df_2_4, output_df_2_4 = test.run_recommendations(user_id=235291, collaborative=0.5, clear_neg=False,
                    vectorizer = 'tfidf', dimred = 'svd', ngram = (1,1), min_df = 1, max_df = 0.9, local = True)
end = time.time()
duration = end - start
print(duration)

  recipe_id                               name liked
0     16741             aunt bee s lentil soup     1
1     10744          delicious chicken pot pie     1
2     16575  just the best barbecue sauce ever     0
3     22782   jo mama s world famous spaghetti     1
4    107997       4 minute spicy garlic shrimp     1
5    212500               mushroom noodle soup     1
6    208930             mary s chiles rellenos     1

,recipe_id,name,content,collaborative,hybrid,rec_score
0,383814,baked cod casserole,1.800800,1.413979,1.607390,1.000
1,255836,chicken parmigina,2.076507,1.011983,1.544245,0.960
2,411372,caesar salad dressing no egg,1.411415,1.514800,1.463107,0.908
3,76593,weymo s accelerated version of grannie s turke...,1.721827,1.035662,1.378744,0.853
4,281914,root vegetables casserole for winter,1.982925,0.756998,1.369961,0.848
5,238415,chicken and rosemary cream rigatoni,1.638573,1.011919,1.325246,0.819
6,51887,feta stuffed chicken with green olives,1.639112,1.008744,1.323928,0.818
7,197905,angel hair pasta with pesto and tomatoes,1.626356,1.007611,1.316984,0.814
8,429766,celery bisque with stilton toasts,1.540033,1.085079,1.312556,0.811
9,367934,chris grilled jalapeno wraps,1.400295,1.215886,1.308091,0.808

47.333410024642944

In [22]:
start = time.time()
input_df_2_5, output_df_2_5 = test.run_recommendations(user_id=235291, collaborative=0.5, clear_neg=False,
                    vectorizer = 'tfidf', dimred = 'svd', ngram = (1,1), min_df = 1, max_df = 0.8, local = True)
end = time.time()
duration = end - start
print(duration)

  recipe_id                               name liked
0     16741             aunt bee s lentil soup     1
1     10744          delicious chicken pot pie     1
2     16575  just the best barbecue sauce ever     0
3     22782   jo mama s world famous spaghetti     1
4    107997       4 minute spicy garlic shrimp     1
5    212500               mushroom noodle soup     1
6    208930             mary s chiles rellenos     1

,recipe_id,name,content,collaborative,hybrid,rec_score
0,383814,baked cod casserole,1.815288,1.414038,1.614663,1.000
1,255836,chicken parmigina,2.066436,1.020752,1.543594,0.956
2,411372,caesar salad dressing no egg,1.420445,1.515723,1.468084,0.910
3,76593,weymo s accelerated version of grannie s turke...,1.719828,1.044676,1.382252,0.857
4,281914,root vegetables casserole for winter,1.988369,0.774026,1.381197,0.856
5,51887,feta stuffed chicken with green olives,1.646730,1.017689,1.332210,0.826
6,36758,chinese chicken chow bake,1.611918,1.048251,1.330085,0.825
7,238415,chicken and rosemary cream rigatoni,1.639290,1.020849,1.330069,0.825
8,197905,angel hair pasta with pesto and tomatoes,1.620703,1.016800,1.318751,0.818
9,429766,celery bisque with stilton toasts,1.553342,1.077765,1.315554,0.816

64.71052885055542

In [25]:
start = time.time()
input_df_2_6, output_df_2_6 = test.run_recommendations(user_id=235291, collaborative=0.5, clear_neg=False,
                    vectorizer = 'tfidf', dimred = 'svd', ngram = (1,1), min_df = 0.1, max_df = 0.9, local = True)
end = time.time()
duration = end - start
print(duration)

  recipe_id                               name liked
0     16741             aunt bee s lentil soup     1
1     10744          delicious chicken pot pie     1
2     16575  just the best barbecue sauce ever     0
3     22782   jo mama s world famous spaghetti     1
4    107997       4 minute spicy garlic shrimp     1
5    212500               mushroom noodle soup     1
6    208930             mary s chiles rellenos     1

,recipe_id,name,content,collaborative,hybrid,rec_score
0,383814,baked cod casserole,1.800870,1.414365,1.607618,1.000
1,255836,chicken parmigina,2.072898,1.024746,1.548822,0.963
2,411372,caesar salad dressing no egg,1.407657,1.522281,1.464969,0.909
3,281914,root vegetables casserole for winter,1.981748,0.763708,1.372728,0.851
4,76593,weymo s accelerated version of grannie s turke...,1.706253,1.032600,1.369427,0.849
5,277802,zingy salsa chicken casserole,2.274460,0.392199,1.333329,0.826
6,51887,feta stuffed chicken with green olives,1.638413,1.021438,1.329926,0.824
7,238415,chicken and rosemary cream rigatoni,1.631600,1.024731,1.328166,0.823
8,197905,angel hair pasta with pesto and tomatoes,1.621250,1.021208,1.321229,0.818
9,429766,celery bisque with stilton toasts,1.553896,1.082809,1.318352,0.816

55.557042837142944