In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
basic_path =  '../../Fed_up/data'

In [3]:
recipes = pd.read_csv(f"{basic_path}/preprocessed/recipe_pp.csv")

In [4]:
test_data = pd.read_csv(f"{basic_path}/test/test_inputs.csv")

In [5]:
test_data.shape

(28861, 5)

In [25]:
from Fed_up.model import get_user_recommendations

def run_recommendations(test_data, user_id=None, collaborative=0.5, clear_neg=False):
    
    if user_id:
        test_case = test_data[test_data.user_id == user_id]
    else:
        test_case = test_data.sample()
        
    inputs = eval(test_case.inputs.values[0])
    
    input_df = pd.DataFrame(columns=['recipe_id', 'liked'])
    for recipe, liked in inputs.items():
        input_df = input_df.append({'recipe_id': recipe, 'liked': liked}, ignore_index=True)

    input_df = input_df.merge(recipes, on='recipe_id', how='left')\
               [['recipe_id', 'name', 'liked']]
    
    display(input_df)
    
    recommendations = get_user_recommendations(user_inputs=inputs, collaborative=collaborative, clear_neg=clear_neg)
    
    output_df = recommendations.merge(recipes, on='recipe_id', how='left') \
                [['recipe_id', 'name', 'content', 'collaborative', 'hybrid', 'rec_score']]
    
    display(output_df.head(10))
    
    return input_df, output_df

In [30]:
input_df, output_df = run_recommendations(test_data, user_id=235291, collaborative=0.5)

  recipe_id                               name liked
0     16741             aunt bee s lentil soup     1
1     10744          delicious chicken pot pie     1
2     16575  just the best barbecue sauce ever     0
3     22782   jo mama s world famous spaghetti     1
4    107997       4 minute spicy garlic shrimp     1
5    212500               mushroom noodle soup     1
6    208930             mary s chiles rellenos     1

,recipe_id,name,content,collaborative,hybrid,rec_score
0,192312,not quite so white chicken chili no tomatoes,0.572669,1.673242,1.122955,1.000
1,119253,mexican style fresh tomatoes and pasta,0.513019,1.673242,1.093130,0.980
2,229880,marko s coleslaw,0.500900,1.673242,1.087071,0.976
3,21452,my mom s coleslaw,0.515316,1.621043,1.068179,0.964
4,231758,organic zesty corn relish,0.310436,1.673242,0.991839,0.913
5,71713,new mexico style red chile enchiladas,0.561016,1.159574,0.860295,0.827
6,4207,microwave gravy,0.699262,0.991424,0.845343,0.817
7,184597,mushrooms in cream sherry sauce,0.892254,0.621976,0.757115,0.758
8,284632,mexican cheeseburger soup,0.794757,0.677021,0.735889,0.744
9,161452,mushrooms on the side,0.791252,0.677021,0.734136,0.743

In [31]:
input_df, output_df = run_recommendations(test_data)

  recipe_id                          name liked
0     24054  southern barbecued beef tips     1

,recipe_id,name,content,collaborative,hybrid,rec_score
0,152030,spinach and cheese casserole,0.281897,0.881934,0.581915,1.000
1,48950,skillet spanish rice,0.325534,0.802830,0.564182,0.970
2,121497,super simple shepherd s pie,0.529770,0.552209,0.540990,0.930
3,89059,steve s world best meatloaf,0.684292,0.139690,0.411991,0.708
4,58608,sweet mustard sauce,0.346332,0.465554,0.405943,0.698
5,290493,shrimp curry goan style,0.281698,0.495842,0.388770,0.669
6,43654,skewered beef strips with spicy honey glaze,0.522121,0.222984,0.372553,0.641
7,91359,southern glazed meatloaf with rosemary gravy,0.567278,0.168403,0.367841,0.633
8,60862,savoury beef,0.538276,0.177404,0.357840,0.615
9,79038,soup kitchen s beefy black eyed pea soup,0.503987,0.209579,0.356783,0.614